"""Modified Followers model and updated Users model

Revision ID: 2dcfeced086e
Revises: a3985b92b941
Create Date: 2024-11-11 21:23:51.474801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2dcfeced086e'
down_revision: Union[str, None] = 'a3985b92b941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('followers_ibfk_1', 'followers', type_='foreignkey')
    op.drop_constraint('followers_ibfk_2', 'followers', type_='foreignkey')
    op.drop_index('ix_followers_following_id', table_name='followers')
    op.drop_index('ix_followers_user_id', table_name='followers')
    
    # Drop the old primary key (if it exists)
    op.drop_constraint('pk_followers', 'followers', type_='primary')

    

    op.add_column('followers', sa.Column('follower_id', sa.Integer(), nullable=False))
    op.add_column('followers', sa.Column('followee_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'followers', 'user', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'followers', 'user', ['followee_id'], ['id'], ondelete='CASCADE')
    op.create_primary_key('pk_followers', 'followers', ['follower_id', 'followee_id'])
    
    # Recreate the indexes for the new columns
    op.create_index('ix_followers_follower_id', 'followers', ['follower_id'], unique=False)
    op.create_index('ix_followers_followee_id', 'followers', ['followee_id'], unique=False)

    op.drop_column('followers', 'following_id')
    op.drop_column('followers', 'user_id')

    # ### end Alembic commands ###

def downgrade() -> None:
    # Drop the new foreign key constraints first
    op.drop_constraint('followers_ibfk_1', 'followers', type_='foreignkey')
    op.drop_constraint('followers_ibfk_2', 'followers', type_='foreignkey')

    op.drop_index('ix_followers_follower_id', table_name='followers')
    op.drop_index('ix_followers_followee_id', table_name='followers')

    # Drop the new primary key (if it exists)
    op.drop_constraint('pk_followers', 'followers', type_='primary')

    # Add the old columns (user_id and following_id) back
    op.add_column('followers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('followers', sa.Column('following_id', sa.Integer(), nullable=False))

    # Recreate the foreign key constraints for the old columns
    op.create_foreign_key('followers_ibfk_2', 'followers', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('followers_ibfk_1', 'followers', 'user', ['following_id'], ['id'], ondelete='CASCADE')

    # Recreate the indexes for the old columns
    op.create_index('ix_followers_user_id', 'followers', ['user_id'], unique=False)
    op.create_index('ix_followers_following_id', 'followers', ['following_id'], unique=False)

    # Recreate the primary key for the old columns
    op.create_primary_key('pk_followers', 'followers', ['user_id', 'following_id'])

    # Drop the new columns
    op.drop_column('followers', 'followee_id')
    op.drop_column('followers', 'follower_id')

    # ### end Alembic commands ###
