name: Deploy to Azure Web App

on:
  push:
    branches:
      - "PreProduction"  # Triggers deployment on pushes to the main branch
  workflow_dispatch:  # Triggers deployment on pushes to the main branch

jobs:
  build:
    if: github.ref == 'refs/heads/PreProduction' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: | 
          npm install
        working-directory: frontend

      - name: Create .env file
        run: |
          echo "${{ secrets.FRONTEND_ENV_PREPRODUCTION }}" > .env
          sed -i 's/|||/\n/g' .env
        working-directory: frontend    

      - name: Build Next.js application
        run: npm run build
        working-directory: frontend

      - name: Create ZIP archive
        run: |
          rm -rf frontend/node_modules/
          zip -r frontend.zip frontend/

      - name: Upload release.zip
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend.zip

  deploy:
    if: github.ref == 'refs/heads/PreProduction' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: ./

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: bookhbdev
          slot-name: production
          publish-profile: ${{ secrets.FRONTEND_AZURE_PUBLISH_PREPRODUCTION }}
          package: frontend.zip
