name: Deploy to Azure Web App

on:
  push:
    branches:
      - "main"  # Triggers deployment on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: | 
          npm install
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_AZURE_SAS_STORAGE=${{ secrets.NEXT_PUBLIC_AZURE_SAS_STORAGE }}
            NEXT_PUBLIC_STORAGE_PROFILE_PICTURES=${{ secrets.NEXT_PUBLIC_STORAGE_PROFILE_PICTURES }}
            NEXT_PUBLIC_STORAGE_BOOKS=${{ secrets.NEXT_PUBLIC_STORAGE_BOOKS}}
            NEXT_PUBLIC_AZURE_SAS_STORAGE_BOOKS=${{ secrets.NEXT_PUBLIC_AZURE_SAS_STORAGE_BOOKS}}" > .env

           echo "Test: algo
            Test2: algo2
            Test3: algo3"
  
        working-directory: frontend

      - name: Build Next.js application
        run: npm run build
        working-directory: frontend

      - name: Create ZIP archive
        run: |
          rm -rf frontend/node_modules/
          zip -r frontend.zip frontend/

      - name: Upload release.zip
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: ./

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: BookHub
          slot-name: production
          publish-profile: ${{ secrets.FRONTEND_AZURE_PUBLISH }}
          package: frontend.zip
