name: Build and deploy Python app to Azure Web App - bookhubapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_NAME: bookhubapi
  DB_HOST: ${{ secrets.DB_HOST_AZURE }}
  DB_PORT: 3306
  DB_USER: bookhubdb_user
  DB_PASSWORD: ${{ secrets.DB_PASSWORD_AZURE }}
  DB_NAME: bookhub
  AZURE_PATH: "./backend"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'

      - name: Change to backend directory
        run: cd backend

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Lock and install dependencies with Poetry
        run: |
          poetry lock
          poetry install
          
      - name: Run Alembic migrations
        run: |
          poetry run alembic upgrade head

      - name: Generate requirements.txt
        run: |
          poetry export --dev --all-extras --without-hashes --format=requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./backend/* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run if the build job succeeds
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'bookhubapi'
          slot-name: 'Production'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
